version: '3'

services:
  serve_db:
    image: mysql:8.0
    environment:
      - MYSQL_USER=root
      - MYSQL_DATABASE=lucid
      - MYSQL_HOST=localhost
      - MYSQL_ROOT_PASSWORD=secret
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - serve_db:/var/lib/mysql'
    networks:
      - production-network

  node-server:
    build:
      context: ./server
      dockerfile: Dockerfile-local
    container_name: node-server
    command: sh -c "npm run migrate && npm run seed && npm start"
    depends_on:
      - serve_db
    links:
      - serve_db
    ports:
      - '3333:3333'
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}
      DB_DATABASE: ${DB_NAME}
      DB_HOST: ${DB_HOST}
    networks:
      - production-network
volumes: 
  serve_db:

networks:
  production-network:
    driver: bridge
